
language: python

python:
- 3.6


install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter
- pip install coveralls codecov 

- pip install pytest
- pip install pytest-cov
- pip install coveralls

services:
  - postgresql

before_script:
  - export FLASK_ENV=testing
  - psql -c "CREATE DATABASE test_ireporter;" -U postgres
  - psql -c "CREATE DATABASE ireporter;" -U postgres

script:
- pytest --cov-report term-missing --cov=app
- coveralls

after_success:
- coveralls
- codeclimate-test-reporter
